//! `Input` domain.

use serde::Serialize;
use serde_json::Value;

/// Parameters of `Input.dispatchMouseEvent`.
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct DispatchMouseEventParams {
    /// Event type (`mousePressed`, `mouseReleased`, `mouseMoved`, ...).
    #[serde(rename = "type")]
    pub event_type: String,
    /// X coordinate in CSS pixels.
    pub x: f64,
    /// Y coordinate in CSS pixels.
    pub y: f64,
    /// Mouse button (`none`, `left`, `middle`, `right`).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub button: Option<String>,
    /// Bitmask of pressed buttons.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub buttons: Option<i64>,
    /// Number of clicks.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub click_count: Option<i64>,
    /// Wheel delta along X (for `mouseWheel` events).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub delta_x: Option<f64>,
    /// Wheel delta along Y (for `mouseWheel` events).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub delta_y: Option<f64>,
}

/// Parameters of `Input.dispatchKeyEvent`.
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct DispatchKeyEventParams {
    /// Event type (`keyDown`, `keyUp`, `rawKeyDown`, `char`).
    #[serde(rename = "type")]
    pub event_type: String,
    /// DOM key value.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// Key code.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    /// Text generated by the key.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub text: Option<String>,
    /// Windows virtual key code.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub windows_virtual_key_code: Option<i64>,
    /// Native virtual key code.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub native_virtual_key_code: Option<i64>,
    /// Modifier bitmask.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub modifiers: Option<i64>,
}

/// Parameters of `Input.insertText`.
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct InsertTextParams {
    /// The text to insert.
    pub text: String,
}

/// Insert text produced by an [`Input.insertText`] call.
pub type InsertTextResult = Value;
