[package]
name = "rustwright-core"
description = "Browser, BrowserContext, Page and Locator abstractions for Rustwright"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
rustwright-browser.workspace = true
rustwright-cdp.workspace = true
rustwright-common.workspace = true
base64.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true

[lints.rust]
unsafe_code = "forbid"
